### ISSUE TITLE
Export website to PDF

### ISSUE THREAD

**Issue by paxcodes** [aaronpk/oauth.net#320]
Can we add a functionality to export this website to PDF? If @aaronpk is alright with this, I can attempt a PR.

**Comment by aaronpk** [comment]
That's an interesting idea, what is the use case? Offline reading?

**Comment by paxcodes** [comment]
Yes. Offline reading. 

I looked a little bit at the code and see that the pages are made through php "scripts" (index.php) --- Not sure yet how to accomplish this. I know documentation tools like mkdocs have plugins to automatically create PDFs out of the documentation. If you approve of this feature request, I'll have to look if there's anything I can learn from mkdocs and can be implemented in this repo without adding too much complexity.

**Comment by aaronpk** [comment]
I'm not opposed to this, but I do think the value of offline reading is only marginal, since most of this site is actually links out to other websites like the specs themselves and blog posts.

Also, unfortunately this site uses an older style of PHP templating where the content isn't stored in a way that's easy to separate from the website navigation, unlike modern blog engines where the content is often stored in a markdown file. It's actually been on my list for a while to rewrite this in a way where the actual content files don't need to do all the `requires` themselves, but it hasn't been a priority tbh.

**Comment by paxcodes** [comment]
> I'm not opposed to this, but I do think the value of offline reading is only marginal, since most of this site is actually links out to other websites like the specs themselves and blog posts.

Good point. I mistook oauth.net as oauth.com --- which has a lot more content and you also happened to write! (I was reading bits of oauth.com at work a few weeks ago, loved the content there --- and so thought of downloading it as a pdf outside of work -- which leads me to this ticker). I only looked at the TOC of oauth.net and didn't realize I was not looking at the same site I was reading a few weeks ago. 

This won't be a priority for me. Other can re-open if they are interested.

**Comment by aaronpk** [comment]
Gotcha! And you can actually get a PDF or ePub of OAuth.com since that site is the online version of my book!

https://oauth2simplified.com/
